"""Registry of the country-level projections the coupling stage compares.

A projection is a named, versioned country-level quantity with units, an
aggregation rule and a prose definition; the registry fixes what each name
*means* so that a comparison in :mod:`src.coupling` cannot quietly change its
inputs. The realization of each projection lives upstream (``src.emissions``,
``src.population``, ``src.area_weighting``); :mod:`src.projections` binds names
to columns.

Two registries are kept. ``PCS_V1`` holds exactly the original pair,
``responsibility_index_v1`` (cumulative production-based CO2 per capita) and
``impact_index_v1`` (station-mean warming rate). ``PCS_V2`` adds the
consumption-based responsibility pair and the people- and area-weighted impact
projections. Each contract carries a SHA-256 ``definition_hash`` over its
fields, mirrored into ``docs/pcs_v1.yaml`` / ``docs/pcs_v2.yaml`` (regenerated by
``python -m src.pcs``), so an edit to a definition is visible in review. A
revised definition is a new name or version, never an in-place edit; names may
not carry variant suffixes such as ``_adjusted`` or ``_corrected``.
"""

from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

PCS_VERSION = "v1"

# The two v1 projections.
RESPONSIBILITY_INDEX = "responsibility_index_v1"
IMPACT_INDEX = "impact_index_v1"
PROJECTION_NAMES: tuple[str, ...] = (RESPONSIBILITY_INDEX, IMPACT_INDEX)

# A name carrying one of these suffixes is an ambiguous variant of an existing
# projection; a revision is a new name or version instead.
FORBIDDEN_SUFFIXES: tuple[str, ...] = (
    "_enhanced", "_variant", "_adjusted", "_hybrid", "_corrected", "_composite",
)

DEFAULT_PCS_YAML_PATH = Path(__file__).resolve().parents[1] / "docs" / "pcs_v1.yaml"

# v2: the v1 pair plus the consumption and weighting lenses. v1 is unchanged.
PCS_VERSION_2 = "v2"
RESPONSIBILITY_CONSUMPTION_INDEX = "responsibility_index_consumption"
RESPONSIBILITY_PRODUCTION_MATCHED_INDEX = "responsibility_index_production_matched"
IMPACT_POPULATION_WEIGHTED_INDEX = "impact_index_population_weighted"
IMPACT_AREA_WEIGHTED_INDEX = "impact_index_area_weighted"
# Registry / yaml order.
PROJECTION_NAMES_V2: tuple[str, ...] = (
    IMPACT_INDEX,
    RESPONSIBILITY_CONSUMPTION_INDEX,
    RESPONSIBILITY_PRODUCTION_MATCHED_INDEX,
    RESPONSIBILITY_INDEX,
    IMPACT_POPULATION_WEIGHTED_INDEX,
    IMPACT_AREA_WEIGHTED_INDEX,
)
DEFAULT_PCS_V2_YAML_PATH = (
    Path(__file__).resolve().parents[1] / "docs" / "pcs_v2.yaml"
)


@dataclass(frozen=True)
class ProjectionContract:
    """One registered projection: name, version, units, and a prose definition.

    ``definition_hash`` is derived from the fields so an edit is detectable.
    """

    name: str
    version: str
    units: str
    aggregation_rule: str
    computation_definition: str

    def __post_init__(self) -> None:
        for field_name in ("name", "version", "units", "aggregation_rule",
                            "computation_definition"):
            if not getattr(self, field_name).strip():
                raise ValueError(f"ProjectionContract {self.name!r}: empty {field_name}")
        bad = [s for s in FORBIDDEN_SUFFIXES if s in self.name]
        if bad:
            raise ValueError(
                f"projection name {self.name!r} carries variant suffix(es) {bad}; "
                "register a new name or version instead"
            )

    @property
    def definition_hash(self) -> str:
        """sha256 over the contract fields."""
        payload = json.dumps(
            {
                "name": self.name,
                "version": self.version,
                "units": self.units,
                "aggregation_rule": self.aggregation_rule,
                "computation_definition": self.computation_definition,
            },
            sort_keys=True,
            ensure_ascii=False,
        )
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------
# v1: the original pair
# ---------------------------------------------------------------------

RESPONSIBILITY_CONTRACT = ProjectionContract(
    name=RESPONSIBILITY_INDEX,
    version=PCS_VERSION,
    units="t CO2 per capita",
    aggregation_rule="sum-then-divide",
    computation_definition=(
        "Cumulative production-based CO2 emissions summed through the analysis "
        "cutoff year, divided by cutoff-year population (tonnes per capita); a "
        "historical-responsibility projection."
    ),
)

IMPACT_CONTRACT = ProjectionContract(
    name=IMPACT_INDEX,
    version=PCS_VERSION,
    units="degC per decade",
    aggregation_rule="unweighted mean across city-locations",
    computation_definition=(
        "Country mean of the per-city-location Theil-Sen warming slopes over the "
        "analysis window (degrees Celsius per decade); a warming-exposure projection."
    ),
)

PCS_V1: dict[str, ProjectionContract] = {
    RESPONSIBILITY_CONTRACT.name: RESPONSIBILITY_CONTRACT,
    IMPACT_CONTRACT.name: IMPACT_CONTRACT,
}


# ---------------------------------------------------------------------
# v2: the consumption and weighting lenses
# ---------------------------------------------------------------------

RESPONSIBILITY_CONSUMPTION_CONTRACT = ProjectionContract(
    name=RESPONSIBILITY_CONSUMPTION_INDEX,
    version=PCS_VERSION_2,
    units="t CO2 per capita",
    aggregation_rule="sum-then-divide over the consumption-available window",
    computation_definition=(
        "Cumulative consumption-based CO2 emissions (emissions counted where goods "
        "are consumed) summed over each country's consumption-available window "
        "[first year consumption data exists .. analysis cutoff], divided by "
        "cutoff-year population (tonnes per capita); a consumption-based "
        "historical-responsibility projection."
    ),
)

RESPONSIBILITY_PRODUCTION_MATCHED_CONTRACT = ProjectionContract(
    name=RESPONSIBILITY_PRODUCTION_MATCHED_INDEX,
    version=PCS_VERSION_2,
    units="t CO2 per capita",
    aggregation_rule="sum-then-divide over the consumption-available window",
    computation_definition=(
        "Cumulative production-based CO2 emissions summed over the SAME "
        "consumption-available window as responsibility_index_consumption, divided "
        "by cutoff-year population (tonnes per capita); the window-matched "
        "production baseline for an apples-to-apples production-vs-consumption "
        "responsibility comparison."
    ),
)

IMPACT_POPULATION_WEIGHTED_CONTRACT = ProjectionContract(
    name=IMPACT_POPULATION_WEIGHTED_INDEX,
    version=PCS_VERSION_2,
    units="degC per decade",
    aggregation_rule="population-weighted mean across city-locations",
    computation_definition=(
        "Country mean of the per-city-location Theil-Sen warming slopes weighted "
        "by each location's population (sampled from a static population grid at "
        "its coordinates), degrees Celsius per decade; a people-weighted "
        "warming-exposure projection -- the warming the average resident "
        "experiences, rather than the average station."
    ),
)

IMPACT_AREA_WEIGHTED_CONTRACT = ProjectionContract(
    name=IMPACT_AREA_WEIGHTED_INDEX,
    version=PCS_VERSION_2,
    units="degC per decade",
    aggregation_rule="cos(latitude) area-weighted mean across gridded land cells",
    computation_definition=(
        "Country mean of per-grid-cell Theil-Sen warming slopes from the Berkeley "
        "Earth 1-degree gridded field over the analysis window, each cell assigned "
        "to a country via the GPW national-identifier grid and weighted by "
        "cos(latitude) so every unit of land area counts equally (degrees Celsius "
        "per decade); an area-weighted warming-exposure projection -- the warming "
        "of the average square kilometre, rather than the average station. "
        "cos(latitude) weighting is required because a temperature trend is an "
        "intensive field, the mirror of the population-count rule where it is "
        "forbidden."
    ),
)


PCS_V2: dict[str, ProjectionContract] = {
    IMPACT_CONTRACT.name: IMPACT_CONTRACT,
    RESPONSIBILITY_CONSUMPTION_CONTRACT.name: RESPONSIBILITY_CONSUMPTION_CONTRACT,
    RESPONSIBILITY_PRODUCTION_MATCHED_CONTRACT.name: (
        RESPONSIBILITY_PRODUCTION_MATCHED_CONTRACT
    ),
    RESPONSIBILITY_CONTRACT.name: RESPONSIBILITY_CONTRACT,
    IMPACT_POPULATION_WEIGHTED_CONTRACT.name: IMPACT_POPULATION_WEIGHTED_CONTRACT,
    IMPACT_AREA_WEIGHTED_CONTRACT.name: IMPACT_AREA_WEIGHTED_CONTRACT,
}


def validate_registry(registry: dict[str, ProjectionContract] = PCS_V1) -> None:
    """Check that the v1 registry holds exactly the two v1 projections.

    Raises:
        ValueError: if the registry's names differ from :data:`PROJECTION_NAMES`
            or a key disagrees with its contract name.
    """
    if set(registry) != set(PROJECTION_NAMES):
        raise ValueError(
            f"PCS {PCS_VERSION} must contain exactly {sorted(PROJECTION_NAMES)}, "
            f"got {sorted(registry)}"
        )
    for key, contract in registry.items():
        if key != contract.name:
            raise ValueError(f"registry key {key!r} != contract name {contract.name!r}")


def validate_registry_v2(registry: dict[str, ProjectionContract] = PCS_V2) -> None:
    """Check that the v2 registry holds exactly the registered v2 names.

    Raises:
        ValueError: if the registry's names disagree with :data:`PROJECTION_NAMES_V2`,
            or a key disagrees with its contract name.
    """
    if set(registry) != set(PROJECTION_NAMES_V2):
        raise ValueError(
            f"PCS {PCS_VERSION_2} must register exactly "
            f"{sorted(PROJECTION_NAMES_V2)}, got {sorted(registry)}"
        )
    for key, contract in registry.items():
        if key != contract.name:
            raise ValueError(f"registry key {key!r} != contract name {contract.name!r}")


# Checked at import so drift fails loudly (like FeatureSchema.__post_init__).
validate_registry()
validate_registry_v2()


# ---------------------------------------------------------------------
# YAML mirror (deterministic, dependency-free; same idea as src.feature_schema)
# ---------------------------------------------------------------------


def _yaml_scalar(value: str) -> str:
    """Double-quote a string scalar with minimal escaping (deterministic)."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def to_yaml(
    registry: dict[str, ProjectionContract] = PCS_V1,
    version: str = PCS_VERSION,
    names: tuple[str, ...] = PROJECTION_NAMES,
    header: str = "# PCS -- generated mirror of src.pcs.PCS_V1 (the semantic registry).",
) -> str:
    """Serialize a registry to a deterministic YAML string (the doc mirror).

    The Python dataclasses are the in-repo source of truth; this is a review /
    diff artifact (including each contract's ``definition_hash``), regenerated by
    :func:`main`. Defaults serialize the v1 registry byte-for-byte; pass the v2
    arguments (and v2 `header`) to mirror the v2 registry.
    """
    lines = [
        header,
        "# Canonical source is the Python dataclasses; regenerate via:",
        "#   uv run python -m src.pcs",
        f"version: {_yaml_scalar(version)}",
        "projections:",
    ]
    for name in names:
        c = registry[name]
        lines.extend(
            [
                f"  - name: {_yaml_scalar(c.name)}",
                f"    version: {_yaml_scalar(c.version)}",
                f"    units: {_yaml_scalar(c.units)}",
                f"    aggregation_rule: {_yaml_scalar(c.aggregation_rule)}",
                f"    computation_definition: {_yaml_scalar(c.computation_definition)}",
                f"    definition_hash: {_yaml_scalar(c.definition_hash)}",
            ]
        )
    return "\n".join(lines) + "\n"


def write_yaml(
    registry: dict[str, ProjectionContract] = PCS_V1,
    path: Path = DEFAULT_PCS_YAML_PATH,
    version: str = PCS_VERSION,
    names: tuple[str, ...] = PROJECTION_NAMES,
    header: str = "# PCS -- generated mirror of src.pcs.PCS_V1 (the semantic registry).",
) -> Path:
    """Write the YAML mirror of `registry` to `path` (parents created)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(to_yaml(registry, version, names, header), encoding="utf-8")
    return path


_PCS_V2_HEADER = "# PCS -- generated mirror of src.pcs.PCS_V2 (the wide semantic registry)."


def to_yaml_v2() -> str:
    """Deterministic YAML mirror of the v2 registry."""
    return to_yaml(PCS_V2, PCS_VERSION_2, PROJECTION_NAMES_V2, _PCS_V2_HEADER)


def main() -> None:
    """Regenerate the YAML mirrors and print a one-line summary per projection."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    validate_registry()
    validate_registry_v2()
    out = write_yaml()
    out_v2 = write_yaml(
        PCS_V2, DEFAULT_PCS_V2_YAML_PATH, PCS_VERSION_2, PROJECTION_NAMES_V2,
        _PCS_V2_HEADER,
    )
    print(f"PCS {PCS_VERSION}: {len(PCS_V1)} projections")
    for name in PROJECTION_NAMES:
        c = PCS_V1[name]
        print(f"  {c.name} [{c.units}] hash={c.definition_hash[:12]}…")
    print(f"PCS {PCS_VERSION_2}: {len(PCS_V2)} projections")
    for name in PROJECTION_NAMES_V2:
        c = PCS_V2[name]
        print(f"  {c.name} [{c.units}] hash={c.definition_hash[:12]}…")
    print(f"wrote {out} and {out_v2}")


if __name__ == "__main__":
    main()
